version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install
  pre_build:
    commands:
      - aws --version  # Verify AWS CLI installation
  build:
    commands:
      - aws cloudformation validate-template --template-body file://s3-template.yaml

