version: 0.2

phases:
  install:
    commands:
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install
  pre_build:
    commands:
      - aws --version  
  build:
    commands:
      - aws cloudformation validate-template --template-body file://s3-kms.yml
      - echo "validation completed"
artifacts:
  files:
    - s3-kms.yml



