AWSTemplateFormatVersion: 2010-09-09

Parameters:
  VersioningStatus:
    Type: String
    Description: "Enable versioning for the S3 bucket (Enabled/Disabled)"
    Default: "Enabled"
    AllowedValues: ["Enabled", "Disabled"]
  AccessControl:
    Type: String
    Description: "Access control for the S3 bucket (Private/PublicRead/PublicReadWrite)"
    Default: "Private"
    AllowedValues: ["Private", "PublicRead", "PublicReadWrite"]
  LifecycleStatus:
    Type: String
    Description: "Enable lifecycle for the S3 bucket (Enabled/Disabled)"
    Default: "Enabled"
    AllowedValues: ["Enabled", "Disabled"]
  LoggingPrefix:
    Type: String
    Description: "Log file prefix for the S3 bucket"
    Default: "testlog"
  TagKey:
    Type: String
    Description: "Environment tag for the S3 bucket"
    Default: "env"
  TagValue:
    Type: String
    Description: "Environment tag for the S3 bucket"
    Default: "test"
  EncryptionSSEAlgorithm:
    Type: String
    Description: "SSE algorithm for bucket encryption"
    Default: "aws:kms"
    AllowedValues: ["aws:kms", "AES256"]
  KMSMasterKeyID:
    Type: String
    Description: "ARN of the KMS master key for bucket encryption"
    Default: "arn:aws:kms:us-east-1:872389479602:key/272ded58-3371-4a70-a8d5-a0a652e6f21e"

Resources:
  jtestbucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      VersioningConfiguration:
        Status: !Ref VersioningStatus
      AccessControl: !Ref AccessControl
      LifecycleConfiguration:
        Rules:
          - Id: GlacierRule
            Prefix: glacier
            Status: !Ref LifecycleStatus
            ExpirationInDays: 365
            Transitions:
              - TransitionInDays: 1
                StorageClass: GLACIER
      LoggingConfiguration:
        LogFilePrefix: !Ref LoggingPrefix
      Tags:
        - Key: !Ref TagKey
          Value: !Ref TagValue
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: !Ref EncryptionSSEAlgorithm
              KMSMasterKeyID: !Ref KMSMasterKeyID

Outputs:
  BucketName:
    Description: "Name of the created S3 bucket"
    Value: !Ref jtestbucket
